config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  root 'locations#index'

    resources :locations do
      resources :salons #, shallow: true
    end

    resources :salons do
      resources :passes #, shallow: true
    end

    resources :passes

    get 'download/:serial_number' , to: 'passes#download', as: 'download'
    get 'wallet/:serial_number' , to: 'passes#wallet', as: 'wallet'
    get 'check/:barcode_message' , to: 'passes#check', as: 'check_pass'

end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :salons, dependent: :destroy
  validates :name, presence: true
end

app/models/pass.rb
class Pass < ActiveRecord::Base
  belongs_to :salon
  validates :user_name, :user_type, :user_phone_number, presence: true
end


# t.string :serial_number
# t.string :authentication_token
# t.string :barcode_message
# t.string :user_name
# t.string :user_phone_number
# t.string :user_type
# t.references :salon, index: true, foreign_key: true

app/models/salon.rb
class Salon < ActiveRecord::Base
  belongs_to :location
  has_many :passes, dependent: :destroy
  validates :name, :topic, :detail_location, :time, :detail_info, :guests, :help, :about, :longitude, :latitude, :foreground_color, :background_color, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def new
    @location = Location.new
  end

  def create
    @location = Location.new(location_params)

    if @location.save
      redirect_to @location
    else
      render 'new'
    end
  end

  def show
    @location = Location.find(params[:id])
    respond_to do |format|
      format.html { @location }
      format.xml  { render xml: @location }
      format.json { render json: @location }
    end
  end

  def index
    @locations = Location.all
    respond_to do |format|
      format.html { @locations }
      format.xml  { render xml: @locations }
      format.json { render json: @locations }
    end
  end

  def edit
    @location = Location.find(params[:id])
  end

  def update
    @location = Location.find(params[:id])
    if @location.update(location_params)
      redirect_to @location
    else
      render 'edit'
    end
  end

  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    redirect_to locations_path
  end

  private
  def location_params
    params.require(:location).permit(:name, :password)
  end
end

app/controllers/passes_controller.rb
require 'sign_pass'

class PassesController < ApplicationController
  def new
    @pass = Pass.new
  end

  def show
    @pass = Pass.find(params[:id])
    render @pass
  end

  def create
    @salon = Salon.find(params[:salon_id])
    @pass = @salon.passes.create(pass_params)
    @pass.serial_number = new_serial_number
    @pass.authentication_token = new_authentication_token
    @pass.barcode_message = new_barcode_message

    if @pass.save
      redirect_to salon_path(@salon)
    else
      render 'new'
    end
  end

  def wallet
    @pass = Pass.where(["serial_number = :p", { p: params[:serial_number] }]).first
    pass_output_path = get_pass_file_path(@pass)
    send_file(pass_output_path,
              type: "application/vnd.apple.pkpass")
  end

  def download
    @pass = Pass.where(["serial_number = :p", { p: params[:serial_number] }]).first
    pass_output_path = get_pass_file_path(@pass)
    send_file(pass_output_path)
  end

  def check
    @pass = Pass.where(["barcode_message = :p", { p: params[:barcode_message] }]).first
    render json: @pass
  end

  def destroy
    @salon = Salon.find(params[:salon_id])
    @pass = @salon.passes.find(params[:id])
    @pass.destroy
    redirect_to salon_path(@salon)
  end

  private
    def pass_params
      params.require(:pass).permit(:user_name, :user_phone_number, :user_type, :real_name, :company_name, :github_id, :mail)
    end

    def new_serial_number
      SecureRandom.hex
    end

    def new_authentication_token
      SecureRandom.hex
    end

    def new_barcode_message
      SecureRandom.hex
    end

    def get_pass_file_path(pass)
      @salon = pass.salon
      @location = @salon.location

      passes_folder_path = "#{Rails.root}/public/assets/passes/"
      template_folder_path = passes_folder_path + "/template"
      target_folder_path = passes_folder_path + "/#{pass.serial_number}"


      if (File.exists?(target_folder_path))
        puts "[ ok ] Deleting existing pass data."
        FileUtils.remove_dir(target_folder_path)
      end

      puts "[ ok ] Creating pass data from template."
      FileUtils.cp_r template_folder_path + "/.", target_folder_path
      json_file_path = target_folder_path + "/pass.json"
      pass_json = JSON.parse(File.read(json_file_path))
      # pass_json["passTypeIdentifier"] = settings.pass_type_identifier
      # pass_json["teamIdentifier"] = settings.team_identifier
      pass_json["serialNumber"] = pass.serial_number
      pass_json["authenticationToken"] = pass.authentication_token
      # pass_json["webServiceURL"] = "http://#{settings.hostname}:#{settings.port}/"
      pass_json["barcode"]["message"] = pass.barcode_message

      pass_json["relevantDate"] = @salon.time

      pass_json["eventTicket"]["primaryFields"][0]["value"] = @salon.topic

      pass_json["eventTicket"]["auxiliaryFields"][0]["value"] = @salon.detail_location
      pass_json["locations"][0]["longitude"] = @salon.longitude
      pass_json["locations"][0]["latitude"] = @salon.latitude
      pass_json["beacons"][0]["proximityUUID"] = @salon.iBeacon

      time_split = @salon.time.split(/T/)
      pass_json["eventTicket"]["auxiliaryFields"][1]["value"] = time_split[0] + "\n" + time_split[1]

      pass_json["eventTicket"]["secondaryFields"][0]["label"] = pass.user_type
      pass_json["eventTicket"]["secondaryFields"][0]["value"] = pass.user_name

      pass_json["eventTicket"]["backFields"][0]["value"] = @salon.detail_info
      pass_json["eventTicket"]["backFields"][1]["value"] = @salon.guests
      pass_json["eventTicket"]["backFields"][2]["value"] = @salon.help
      pass_json["eventTicket"]["backFields"][3]["value"] = @salon.about

      pass_json["eventTicket"]["headerFields"][0]["value"] = @location.name

      pass_json["foregroundColor"] = @salon.foreground_color
      pass_json["backgroundColor"] = @salon.background_color

      File.open(json_file_path, "w") do |f|
        f.write JSON.pretty_generate(pass_json)
      end

      pass_folder_path = target_folder_path
      pass_signing_certificate_path = "#{Rails.root}/vendor/Certificate/Certificates.p12"
      wwdr_certificate_path = "#{Rails.root}/vendor/Certificate/WWDR.pem"
      pass_output_path = passes_folder_path + "/#{pass.serial_number}.pkpass"

      # Remove the old pass if it exists
      if File.exists?(pass_output_path)
        File.delete(pass_output_path)
      end

      # Generate and sign the new pass
      pass_signer = SignPass.new(pass_folder_path, pass_signing_certificate_path, '', wwdr_certificate_path, pass_output_path)
      pass_signer.sign_pass!

      pass_output_path
    end

end

app/controllers/salons_controller.rb
class SalonsController < ApplicationController

  def new
    @salon = Salon.new
  end

  def create
    @location = Location.find(params[:location_id])
    @salon = @location.salons.create(salon_params)
    # redirect_to location_path(@location)
    if @salon.save
      redirect_to @location
    else
      render 'new'
      # redirect_to @location
    end
  end

  def show
    # @location = Location.find(params[:location_id])
    @salon = Salon.find(params[:id])
  end

  def edit
    @salon = Salon.find(params[:id])
  end

  def destroy
    @location = Location.find(params[:location_id])
    @salon = @location.salons.find(params[:id])
    @salon.destroy
    redirect_to location_path(@location)
  end

  private
    def salon_params
      params.require(:salon).permit(:name, :topic, :detail_location, :time, :detail_info, :guests, :help, :about, :longitude, :latitude, :foreground_color, :background_color, :iBeacon)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/passes_helper.rb
module PassesHelper
end

app/helpers/salons_helper.rb
module SalonsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PassServer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

<%= yield %>

<footer class="bs-docs-footer" role="contentinfo">
  <div class="container text-center">
    <p>v0.0.1 T 专属</p>
  </div>
</footer>
</body>
</html>

app/views/locations/_form.html.erb
<div class="container">
<%= form_for @location do |f| %>
  <% if @location.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(@location.errors.count, "error") %></h3>
    <ul>
    <% @location.errors.full_messages.each do |msg| %>
      <li class="text-warning"><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <div class="container form-group">
    <%= f.label :据点 %><br>
    <%= f.text_field :name, class: 'form-control', placeholder: '北京' %>
  </div>
  <!-- <div class="container form-group">
    <%= f.label :密码 %><br>
    <%= f.text_field :password, class: 'form-control', id: "disabledInput" %>
  </div> -->
  <div class="container text-center">
    <%= f.submit :保存据点, class: 'btn btn-default' %>
    <%= link_to '取消', locations_path, class: 'btn btn-info' %>
  </div>
</div>
<% end %>

app/views/locations/edit.html.erb
<div class="container">
<h1>编辑据点</h1>

<%= render 'form' %>
</div>

app/views/locations/index.html.erb
<div class="container">
<h1>T</h1>

<table class="table">
  <tr>
    <th>我们的根据地</th>
  </tr>

  <% @locations.each do |location| %>
    <tr>
      <td><%= link_to location.name, location_path(location) %></td>
      <td>
        <%= link_to '编辑', edit_location_path(location),
                    class: "btn btn-default" %>
        <%= link_to '删除', location_path(location),
                    method: :delete, data: { confirm: '真的吗。。。' },
                    class: "btn btn-danger" %>
      </td>
    </tr>
  <% end %>
</table>
</div>

<div class="container text-center">
<%= link_to '创建新据点', new_location_path,
                class: "btn btn-success" %>
</div>

app/views/locations/new.html.erb
<div class="container">
<h2>建立一个新的 T 据点</h2>

<%= render 'form' %>
</div>

app/views/locations/show.html.erb
<div class="container">
  <h2>
    <%= @location.name %>
    <small><%= link_to '编辑', edit_location_path(@location) %></small>
    <small><%= link_to '据点列表', locations_path %></small>
  </h2>

<h3>沙龙活动</h2>
<%= render @location.salons %>

<h3>添加一期沙龙活动:</h3>
<%= render "salons/form" %>
</div>

app/views/passes/_form.html.erb
<%= form_for([@salon, @salon.passes.build]) do |f| %>
  <% if @pass %>
  <% if @pass.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(@pass.errors.count, "error") %></h3>
    <ul>
      <% @pass.errors.full_messages.each do |msg| %>
      <li class="text-warning"><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <% end %>

  <div class="container form-group">
    <%= f.label :姓名 %><br>
    <%= f.text_field :real_name, class: 'form-control' %>
  </div>
  <div class="container form-group">
    <%= f.label :昵称 %><br>
    <%= f.text_field :user_name, class: 'form-control' , placeholder: '没有就和姓名添一样的吧'%>
  </div>
  <div class="container form-group">
    <%= f.label :所在公司 %><br>
    <%= f.text_field :company_name, class: 'form-control' %>
  </div>
  <div class="container form-group">
    <%= f.label :GitHubID %><br>
    <%= f.text_field :github_id, class: 'form-control' %>
  </div>
  <div class="container form-group">
    <%= f.label :邮箱 %><br>
    <%= f.text_field :mail, class: 'form-control' %>
  </div>
  <div class="container form-group">
    <%= f.label :手机号 %><br>
    <%= f.text_field :user_phone_number, class: 'form-control' %>
  </div>
  <div class="container form-group">
    <%= f.label :类型 %><br>
    <%= f.text_field :user_type, class: 'form-control', placeholder: '负责人,分享嘉宾,特别邀请' %>
  </div>

  <div class="container text-center">
    <%= f.submit :创建Pass, class: 'btn btn-default' %>
    <%= link_to '取消', salon_path(@salon) , class: 'btn btn-info' %>
  </div>
<% end %>

app/views/passes/_pass.html.erb
<dl class="dl-horizontal">
  <dt>名称</dt>
  <dd><%= pass.user_name %></dd>

  <dt>序列号</dt>
  <dd><%= pass.serial_number %></dd>

  <dt>二维码 Code</dt>
  <dd><%= pass.barcode_message %></dd>

  <dt>手机号</dt>
  <dd><%= pass.user_phone_number %></dd>

  <dt>类型</dt>
  <dd><%= pass.user_type %></dd>

  <dt>所在公司</dt>
  <dd><%= pass.company_name %></dd>

  <dt>邮箱</dt>
  <dd><%= pass.mail %></dd>

</dl>

<div class="container text-center">
  <%= link_to '添加到 Wallet', wallet_path(pass.serial_number),
              class: "btn btn-link" %>
  <%= link_to '下载 Pass', download_path(pass.serial_number),
              class: "btn btn-link" %>
  <%= link_to '删除 Pass', [pass.salon, pass],
               method: :delete,
               data: { confirm: '确定删除该 Pass 吗？' },
               class: "btn btn-danger" %>
</div>

app/views/passes/new.html.erb
<div class="container">
<h2>添加一名 Pass 用户:</h2>
<%= render 'form' %>
</div>

app/views/salons/_form.html.erb
<%= form_for([@location, @location.salons.build]) do |f| %>
  <% if @salon %>
  <% if @salon.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(@salon.errors.count, "error") %></h3>
    <ul>
      <% @salon.errors.full_messages.each do |msg| %>
      <li class="text-warning"><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <% end %>

  <div class="container form-group">
    <%= f.label :名称 %><br>
    <%= f.text_field :name, class: 'form-control', placeholder: 'React Native' %>
  </div>
  <div class="container form-group">
    <%= f.label :主题 %><br>
    <%= f.text_field :topic, class: 'form-control', placeholder: 'React Native：移动开发时代的巴别塔' %>
  </div>
  <div class="container form-group">
    <%= f.label :时间 %><br>
    <%= f.text_field :time, class: 'form-control', placeholder: '2016-05-28T13:00-18:00' %>
  </div>
  <div class="container form-group">
    <%= f.label :具体地址 %><br>
    <%= f.text_field :detail_location, class: 'form-control', placeholder: '北京美餐网' %>
  </div>
  <div class="container form-group">
    <%= f.label :经度longitude %><br>
    <%= f.text_field :longitude, class: 'form-control', placeholder: '116.309178', type: 'number' %>
  </div>
  <div class="container form-group">
    <%= f.label :维度latitude %><br>
    <%= f.text_field :latitude, class: 'form-control', placeholder: '39.934223', type: 'number' %>
  </div>
  <div class="container form-group">
    <%= f.label "iBeaconUUID(可选)" %><br>
    <%= f.text_field :iBeacon, class: 'form-control' %>
  </div>
  <div class="container form-group">
    <%= f.label :文字颜色 %><br>
    <%= f.text_field :foreground_color, class: 'form-control', placeholder: 'rgb(45, 45, 45)', value: 'rgb(45, 45, 45)' %>
  </div>
  <div class="container form-group">
    <%= f.label :背景色 %><br>
    <%= f.text_field :background_color, class: 'form-control', placeholder: 'rgb(250, 250, 250)', value: 'rgb(250, 250, 250)' %>
  </div>
  <div class="container form-group">
    <%= f.label :详细信息 %><br>
    <%= f.text_area :detail_info, class: 'form-control' %>
  </div>
  <div class="container form-group">
    <%= f.label :分享嘉宾 %><br>
    <%= f.text_area :guests, class: 'form-control' %>
  </div>
  <div class="container form-group">
    <%= f.label :附加信息 %><br>
    <%= f.text_area :help, class: 'form-control' %>
  </div>
  <div class="container form-group">
    <%= f.label :关于 %><br>
    <%= f.text_area :about, class: 'form-control', value: '我们是一个邀请制的 iOS 社区，想做点有价值、高质量的事，让每个参与者都有所收获。' %>
  </div>
  <div class="container text-center">
    <%= f.submit :创建新一期沙龙, class: 'btn btn-default' %>
    <%= link_to '取消', location_path(@location) , class: 'btn btn-info' %>
  </div>
<% end %>

<!-- t.text     "detail_info"
t.text     "guests"
t.text     "help"
t.text     "about" -->

app/views/salons/_salon.html.erb
<dl class="dl-horizontal">
  <dt>名称</dt>
  <dd><%= link_to salon.name, [salon.location, salon] %></dd>

  <dt>主题</dt>
  <dd><%= salon.topic %></dd>

  <dt>时间</dt>
  <dd<%= salon.time %></dd>
</dl>

<div class="container text-center">
  <!-- <%= link_to '编辑', edit_salon_path(salon),
              class: 'btn btn-default disabled' %> -->
  <%= link_to '删除', [salon.location, salon],
               method: :delete,
               data: { confirm: '确定删除本期沙龙吗？' },
               class: 'btn btn-danger' %>
</div>

app/views/salons/edit.html.erb
<div class="container">
<h1>编辑沙龙</h1>

<%= render 'form' %>
</div>

app/views/salons/new.html.erb
<div class="container">
<h2>添加一期沙龙活动:</h2>
<%= render 'form' %>
</div>

app/views/salons/show.html.erb
<div class="container">

<h2>
  <%= @salon.name %>
  <!-- <small><%= link_to '编辑', edit_salon_path, class: 'btn btn-link disabled' %></small> -->
  <small><%= link_to @salon.location.name, location_path(@salon.location) %></small>
</h2>

<h3>沙龙 Pass 用户:</h3>
<%= render @salon.passes %>

<h3>添加一名 Pass 用户:</h3>
<%= render "passes/form" %>
</div>

app/views/welcome/index.html.erb
<h1>Hello T</h1>

<%= link_to '我们的根据地', controller: 'locations' %>